In [53]:
import pandas as pd
import numpy as np

data = pd.DataFrame({
    'user'     : [' Sahil', 'sahil  ', 'Nirjala', 'nirjala', 'MAHESH', 'Sahil', np.nan, '!!!Error!!!'],
    'age'      : ['28', '28', '  ?', '34', '150', '28', '22', 'Unknown'],
    'spend'    : ['$100.5', '100.5', '85.30', 'not_available', '50.5', '$100.5', '999999', '0.0'],
    'joined'   : ['2023-12-01', '23/12/01', '2023-12-01', 'Dec-2023', '2023-12-02', '2023-12-01', np.nan, 'yesterday']
})

display(data)
display(data.info())

          user      age          spend      joined
0        Sahil       28         $100.5  2023-12-01
1      sahil         28          100.5    23/12/01
2      Nirjala        ?          85.30  2023-12-01
3      nirjala       34  not_available    Dec-2023
4       MAHESH      150           50.5  2023-12-02
5        Sahil       28         $100.5  2023-12-01
6          NaN       22         999999         NaN
7  !!!Error!!!  Unknown            0.0   yesterday

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   user    7 non-null      object
 1   age     8 non-null      object
 2   spend   8 non-null      object
 3   joined  7 non-null      object
dtypes: object(4)
memory usage: 388.0+ bytes

None

1 . Cleaning

In [54]:

data['age'] = pd.to_numeric(data['age'] , errors='coerce')
data['spend'] = pd.to_numeric(data['spend'] , errors='coerce')

display(data)

          user    age     spend      joined
0        Sahil   28.0       NaN  2023-12-01
1      sahil     28.0     100.5    23/12/01
2      Nirjala    NaN      85.3  2023-12-01
3      nirjala   34.0       NaN    Dec-2023
4       MAHESH  150.0      50.5  2023-12-02
5        Sahil   28.0       NaN  2023-12-01
6          NaN   22.0  999999.0         NaN
7  !!!Error!!!    NaN       0.0   yesterday

In [55]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy='mean')
data[['age','spend']] = imputer.fit_transform(data[['age','spend']])

In [56]:
data

          user         age      spend      joined
0        Sahil   28.000000  200047.06  2023-12-01
1      sahil     28.000000     100.50    23/12/01
2      Nirjala   48.333333      85.30  2023-12-01
3      nirjala   34.000000  200047.06    Dec-2023
4       MAHESH  150.000000      50.50  2023-12-02
5        Sahil   28.000000  200047.06  2023-12-01
6          NaN   22.000000  999999.00         NaN
7  !!!Error!!!   48.333333       0.00   yesterday

In [57]:
data['age'] = data['age'].astype('int')
data['age']

0     28
1     28
2     48
3     34
4    150
5     28
6     22
7     48
Name: age, dtype: int64

In [58]:
data['user'] = data['user'].str.strip().str.title()

In [59]:
for u in range(0,data.shape[0]):
    c = 2
    for i in range(u+1,data.shape[0]):
        if data.loc[u,'user'] == data.loc[i,'user']:
            data.loc[i,'user'] += str(c)
            c+=1
    c = 0

data['user']

0          Sahil
1         Sahil2
2        Nirjala
3       Nirjala2
4         Mahesh
5         Sahil3
6            NaN
7    !!!Error!!!
Name: user, dtype: object

In [60]:
data.loc[7,'user'] = np.nan

In [62]:
data.fillna({'user' : 'NAME MISSING'},inplace=True)
data['user']

0           Sahil
1          Sahil2
2         Nirjala
3        Nirjala2
4          Mahesh
5          Sahil3
6    NAME MISSING
7    NAME MISSING
Name: user, dtype: object

In [63]:
data

           user  age      spend      joined
0         Sahil   28  200047.06  2023-12-01
1        Sahil2   28     100.50    23/12/01
2       Nirjala   48      85.30  2023-12-01
3      Nirjala2   34  200047.06    Dec-2023
4        Mahesh  150      50.50  2023-12-02
5        Sahil3   28  200047.06  2023-12-01
6  NAME MISSING   22  999999.00         NaN
7  NAME MISSING   48       0.00   yesterday

In [ ]:
MONTHS = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"]
day = ['tomorrow','yesterday','today']
for d in range(0,data.shape[0]):
    for j in MONTHS:
        if data.loc[d,'joined'] == j or data.loc[d,'joined'] == j[0:3]:
            data.loc[d,'joined'] = f'2023-{j.index()}-'